-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Collection CASCADE;
DROP TABLE IF EXISTS CollectionEntry CASCADE;
DROP TABLE IF EXISTS Deck CASCADE;
DROP TABLE IF EXISTS DeckEntry CASCADE;
DROP TABLE IF EXISTS Account CASCADE;
DROP TABLE IF EXISTS ValueProgress CASCADE;